apiVersion: v1alpha1
sts-region: us-west-2
discovery:
  jobs:
    - type: sagemaker-endpoints
      regions:
        - us-west-2
      length: 120
      period: 60
      statistics:
        - Average
        - Sum
        - Minimum
        - Maximum
      metrics:
        - name: CPUUtilization    
        - name: MemoryUtilization  
    - type: sagemaker-training
      regions:
        - us-west-2
      length: 120
      period: 60
      statistics:
        - Average
        - Sum
        - Minimum
        - Maximum
      metrics:
        - name: class_1_f1score       
    - type: sagemaker-processing
      regions:
        - us-west-2
      length: 120
      period: 60
      statistics:
        - Average
        - Sum
        - Minimum
        - Maximum
      metrics:
        - name: DiskUtilization           
    - type: sagemaker
      regions:
        - us-west-2
      length: 120
      period: 60
      statistics:
        - Average
        - Sum
        - Minimum
        - Maximum
      metrics:
        - name: Invocations            